site_name: Yummy Game Server
nav:
    - Home: index.md
    - Installation: installation.md
    - Connection: connection.md
    - Messages:
        - Authentication: message/auth.md
        - User: message/user.md
        - Room: message/room.md
        - General objects: message/general-objects.md
    - Lua:
        - Scripting: lua/scripting.md
        - Auth API's: lua/auth.md
        - User API's: lua/user.md
    - Environtment variables: env-variables.md
    - Unit test: unit-test.md
    - Code coverage: code-coverage.md
    
theme:
  name: material

extra_css:
  - css/extra.css

repo_url: https://github.com/erhanbaris/yummy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true