[workspace]
members = [
    "macros",
    "server",
    "manager",
    "database",
    "general"
]

[workspace.dependencies]
general = { path = "./general", features = ["stateless"] }
manager = { path = "./manager", features = ["stateless"] }
server = { path = "./server", features = ["stateless"] }
database = { path = "./database" }
macros = { path = "./macros" }