[workspace]
members = [
    "macros",
    "server",
    "manager",
    "database",
    "general"
]

[workspace.dependencies]
general = { path = "./general", features = ["stateless"] }
manager = { path = "./manager", features = ["stateless"] }
server = { path = "./server", features = ["stateless"] }
database = { path = "./database" }
macros = { path = "./macros" }

redis = { version = "0.22.1", features = ["r2d2", "tokio-comp"] }
r2d2 =  { version = "0.8.10" }
actix = "0.13"
tokio = { version = "1.23.0", features = ["full"] }
bytes = "1.3.0"