[workspace]
members = [
    "macros",
    "server",
    "manager",
    "database",
    "general"
]

[workspace.dependencies]
general = { path = "./general", features = [] }
manager = { path = "./manager", features = [] }
server = { path = "./server", features = [] }
database = { path = "./database" }
macros = { path = "./macros" }

redis = { version = "0.22.1", features = ["r2d2", "tokio-comp"] }
r2d2 =  { version = "0.8.10" }
actix = "0.13"
actix-web = { version = "4", features = ["rustls"] }
tokio = { version = "1.23.0", features = ["full"] }
bytes = "1.3.0"
tracing-subscriber = "0.3"
serde = { version = "1.0.151", features = ["derive", "rc"] }
rustls = "0.20.7"
rustls-pemfile = "1.0.1"
