[package]
name = "general"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = { version = "4", features = ["rustls"] }

thiserror = "1.0.37"
anyhow = "1.0.66"
harsh = "0.2.2"
secrecy = { version = "0.8.0", features = ["serde"] }

chrono = "0.4.23"
jsonwebtoken = "8.1.1"
hmac = "0.12.1"
sha2 = "0.10"
futures-util = "0.3.25"

lockfree = "0.5.1"

serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
serde_repr = "0.1"
uuid = { version = "1.2", features = ["serde", "v4"] }

tracing = "0.1"
tracing-subscriber = "0.3"
