[package]
name = "manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general = { path = "../general" }
database = { path = "../database" }
macros = { path = "../macros" }

actix = "0.13"
actix-web-actors = "4.1.0"
actix-web = { version = "4", features = ["rustls"] }
actix-broker = "0.4.3"

thiserror = "1.0.37"
anyhow = "1.0.66"
secrecy = { version = "0.8.0", features = ["serde"] }

serde = { version = "1.0.151", features = ["derive", "rc"] }
serde_json = "1.0.89"
serde_repr = "0.1"
uuid = { version = "1.2", features = ["serde", "v4"] }

tracing = "0.1"
tracing-subscriber = "0.3"

validator = { version = "0.16", features = ["derive"] }
serde_trim = "0.4.0"

moka = { version = "0.9.6", features = ["future"] }
rand = "0.8.5"
