[package]
name = "lua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general.workspace = true
cache.workspace = true

thiserror.workspace = true
anyhow.workspace = true
mlua.workspace = true