[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
database = { path = "../database" }
manager = { path = "../manager" }

actix = "0.13"
actix-cors = "0.6.4"
actix-web = { version = "4", features = ["rustls"] }
actix-web-actors = "4.1.0"
actix-files = "0.6.2"

serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_repr = "0.1"
uuid = { version = "1.2", features = ["serde", "v4"] }

log = "0.4"
env_logger = "0.9.3"

chrono = "0.4.22"
jsonwebtoken = "8.1.1"
harsh = "0.2.2"

num-derive = "0.3.3"
num-traits = "0.2.15"

strum = "0.24"
strum_macros = "0.24"

thiserror = "1.0.37"
anyhow = "1.0.66"
secrecy = { version = "0.8.0", features = ["serde"] }
hmac = { version = "0.12", features = ["std"] }
sha2 = "0.10"

tracing = "0.1"
tracing-subscriber = "0.3"
tracing-opentelemetry = "0.18.0"