[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
r2d2 = "0.8.10"
diesel = { version = "2.0.2", features = ["sqlite", "numeric", "r2d2", "chrono"] }
diesel-derive-enum = { version = "1.1.2", features = ["sqlite"] }
uuid = { version = "1.2", features = ["serde", "v4"] }
thiserror = "1.0.37"
anyhow = "1.0.66"
secrecy = "0.8.0"
chrono = "0.4.23"

[target.'cfg(windows)'.dependencies]
libsqlite3-sys = { version = "^0", features = ["bundled"] }
