
# UserType's
USER_TYPE_USER: int
USER_TYPE_MOD: int
USER_TYPE_ADMIN: int

# UserMetaAccess's
USER_META_ACCESS_ANONYMOUS: int
USER_META_ACCESS_USER: int
USER_META_ACCESS_FRIEND: int
USER_META_ACCESS_ME: int
USER_META_ACCESS_MOD: int
USER_META_ACCESS_ADMIN: int
USER_META_ACCESS_SYSTEM: int

# MetaAction
META_ACTION_ONLY_ADD_OR_UPDATE: int
META_ACTION_REMOVE_UNUSED_METAS: int
META_ACTION_REMOVE_ALL_METAS: int

# RoomUserType
ROOM_TYPE_TYPE_USER: int
ROOM_TYPE_TYPE_MODERATOR: int
ROOM_TYPE_TYPE_OWNER: int
