name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install grcov
      run: |
        rustup component add llvm-tools-preview
        cargo install grcov
    
    - name: Check
      run: cargo check
      env:
        RUSTFLAGS: "-Cinstrument-coverage"
    
    - name: Check stateless
      run: cargo check --features stateless
      env:
        RUSTFLAGS: "-Cinstrument-coverage"
    
    - name: Run tests
      run: cargo test --all
      env:
        LLVM_PROFILE_FILE: "target/coverage/prof/%p-%m.profraw"
        RUSTFLAGS: "-Cinstrument-coverage"

    - name: Create coverage report
      run: |
        grcov \
          --source-dir . \
          --binary-path target/debug \
          --branch \
          --excl-start 'mod test \{' \
          --excl-start 'mod tests \{' \
          --ignore 'tests/*' \
          --ignore server/src/main.rs \
          --ignore server/src/api/websocket/client.rs \
          --ignore "*test.rs" \
          --ignore "*tests.rs" \
           -t lcov \
           -o lcov.info \
           target/coverage/prof

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        files: lcov.info
        fail_ci_if_error: false

