name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Check 
      run: cargo check
    
    - name: Check - stateless
      run: cargo check --features stateless

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: lcov.info
        fail_ci_if_error: false
  
  stateless-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
  
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '--features stateless -- --test-threads 1'

    - name: Run tests - stateless
      run: cargo test --all --features stateless
      env:
        DEFAULT_REDIS_URL: "redis://redis/"
        RUSTFLAGS: "-Cinstrument-coverage"


    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: lcov.info
        fail_ci_if_error: false
