name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install grcov
      run: |
        rustup component add llvm-tools-preview
        cargo install grcov
    
    - name: Check
      run: cargo check
      env:
        RUSTFLAGS: "-Cinstrument-coverage"
  
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0

    - name: Check stateless
      run: cargo check --features stateless
      env:
        RUSTFLAGS: "-Cinstrument-coverage"
    
    - name: Run tests
      run: cargo test --all
      env:
        LLVM_PROFILE_FILE: "target/coverage/normal/%p-%m.profraw"
        RUSTFLAGS: "-Cinstrument-coverage"
    
    - name: Run tests - stateless
      run: cargo test --all --features stateless
      env:
        DEFAULT_REDIS_URL: "redis://redis/"
        LLVM_PROFILE_FILE: "target/coverage/stateless/%p-%m.profraw"
        RUSTFLAGS: "-Cinstrument-coverage"

    - name: Create coverage report
      run: |
        grcov . \
            --binary-path ./target/debug/deps/ \
            --source-dir . \
            --ignore-not-existing \
            --excl-start 'mod test* \{' \
            --ignore 'tests/*' \
            --ignore server/src/main.rs \
            --ignore server/src/api/websocket/client.rs \
            --ignore general/src/client.rs \
            --ignore "*test.rs" \
            --ignore "*tests.rs" \
            -t lcov \
            -o lcov.info

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: lcov.info
        fail_ci_if_error: false

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}
        path-to-lcov: lcov.info