name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
    - name: Tests
      run: cargo test --all
    - name: Check stateless
      run: cargo check --features stateless
    - name: Tests stateless
      run: cargo test --all --features stateless
